# Generated by Django 4.1.3 on 2022-11-28 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='New Team', max_length=200)),
                ('team_grounp', models.PositiveIntegerField()),
                ('games_played', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('wins', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
                ('ties', models.PositiveIntegerField()),
                ('goals_scored', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
