# Generated by Django 4.1.3 on 2022-11-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='games_played',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
