# Generated by Django 4.1.3 on 2022-11-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0003_alter_team_games_played_alter_team_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='games_played',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
