# Generated by Django 4.1.3 on 2022-11-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0004_position_player_position_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='position_id',
            new_name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_nation', to='tableapi.nationality'),
        ),
    ]
