# Generated by Django 4.1.3 on 2022-11-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0005_nationality_rename_position_id_player_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nationality',
            new_name='nationality_id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='position_id',
        ),
    ]
