# Generated by Django 4.1.3 on 2022-11-29 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0006_rename_nationality_player_nationality_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_nation', to='tableapi.nationality'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_position', to='tableapi.position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='team_players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tableapi.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tableapi.team')),
            ],
        ),
    ]
