# Generated by Django 4.1.3 on 2022-12-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0007_alter_player_nationality_id_alter_player_position_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(default='Stadium', max_length=200)),
                ('address', models.CharField(default='Doha, Qatar', max_length=200)),
            ],
        ),
    ]
