# Generated by Django 4.1.3 on 2022-12-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0008_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_match', models.DateTimeField(auto_now=True, null=True)),
                ('game_result', models.CharField(choices=[('W', 'Win'), ('L', 'Lost'), ('D', 'Draw')], default='D', max_length=1)),
                ('goals_score', models.CharField(default='0:0', max_length=100)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tableapi.venue')),
            ],
        ),
    ]
