# Generated by Django 4.1.3 on 2022-12-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0010_remove_game_game_result_remove_game_goals_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tableapi.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tableapi.team')),
            ],
        ),
    ]
