# Generated by Django 4.1.3 on 2022-12-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0011_team_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goal_dif',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_lost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
